apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ parameters.name }}
  namespace: ${{ parameters.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ parameters.name }}
  template:
    metadata:
      labels:
        app: ${{ parameters.name }}
    spec:
      containers:
        - name: backstage
          image: ${{ secrets.DOCKER_USERNAME }}/${{ parameters.name }}:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources: # Add this section
            requests:
              memory: "512Mi" # Set the memory request to 512 Megabytes
            limits:
              memory: "1Gi" # Set the memory limit to 1 Gigabyte
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ parameters.name }}.service
  namespace: ${{ parameters.name }}
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ${{ parameters.name }}-http
  namespace: ${{ parameters.name }}
spec:
  virtualhost:
    fqdn: ${{ parameters.proxy }}
    tls:
      secretName: backstage-cert
  routes:
    - services:
        - name: ${{ parameters.name }}.service
          port: 80
