name: Retrieve Secrets and Trigger Build

on:
  repository_dispatch:
    types:
      - 00-retrieve-secrets

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: getRepo
        id: get-repo
        run: |
          echo "REPO=${{ github.event.client_payload.repo_url }}" >> $GITHUB_ENV
          echo "Value of REPO: $REPO"  # (DEBUG) Print the REPO value for tracking
          
      - name: Trigger Cross-Repository Dispatch
        env:
          SOME_EVENT: "01-start-build-and-push-image"
          REPO : ${{ github.event.client_payload.repo_url }}
          GITHUB_TOKEN: ${{ github.event.client_payload.github_token }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          KUBE_CREDENTIALS: ${{ secrets.KUBE_CREDENTIALS }}
        run: |
          
          REPO_URL="${{ env.REPO }}"
          REPO_NAME="$(basename $REPO_URL)"
          OWNER_NAME="$(dirname $REPO_URL)"
          OWNER_NAME="$(basename $OWNER_NAME)"

          URL="https://api.github.com/repos/${OWNER_NAME}/${REPO_NAME}/dispatches"

          echo "REPO_URL: $REPO_URL"
          echo "REPO_NAME: $REPO_NAME"
          echo "OWNER_NAME: $OWNER_NAME"
          echo "Constructed URL: $URL"

          curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --request POST \
            --data "{\"event_type\": \"$SOME_EVENT\", \"client_payload\": { \"docker_username\": \"$DOCKER_USERNAME\", \"docker_password\": \"$DOCKER_PASSWORD\", \"kube_credentials\": \"$KUBE_CREDENTIALS\",\"github_token\": \"$GITHUB_TOKEN\"}}" \
            "$URL"
