name: Retrieve Secrets and Trigger Build

on:
  repository_dispatch:
    types:
      - 00-retrieve-secrets

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: getReq
        env:
          REPO: ${{github.event.client_payload.repo_url }}
      - name: Retrieve Secrets
        id: secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "KUBE_CREDENTIALS=${{ secrets.KUBE_CREDENTIALS }}" >> $GITHUB_ENV  # Add this line to retrieve Kubeconfig data
          echo "GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN}}""

      - name: Trigger Cross-Repository Dispatch
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOME_EVENT: 01-start-build-and-push-image
          DOCKER_USERNAME: $DOCKER_USERNAME
          DOCKER_PASSWORD: $DOCKER_PASSWORD
          KUBE_CREDENTIALS: $KUBE_CREDENTIALS
          run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $AUTH_TOKEN" \
            --request POST \
            --data "{\"event_type\": \"01-start-build-and-push-image\", \"client_payload\": { \"docker_username\": \"$DOCKER_USERNAME\", \"docker_password\": \"$DOCKER_PASSWORD\", \"kube_credentials\": \"$KUBE_CREDENTIALS\"}}" \
            https://api.github.com/repos/REPO/dispatches

        