name: Retrieve Secrets and Trigger Build

on:
  release:
      types: [published]
  #repository_dispatch:
    #types:
      #- 00-retrieve-secrets

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Retrieve Secrets
        id: secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "KUBE_CREDENTIALS=${{ secrets.KUBE_CREDENTIALS }}" >> $GITHUB_ENV  # Add this line to retrieve Kubeconfig data
          
      - name: Dispatch Event to Repo B (Trigger Docker Build)
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.repos.createDispatchEvent({
              repo: ${{ inputs.repo-url }},
              event_type: '01-start-build-and-push-image',
              client_payload: {
                docker_username: process.env.DOCKER_USERNAME,
                docker_password: process.env.DOCKER_PASSWORD,
                kube_credentials:process.env.KUBE_CREDENTIALS
              }
            });

      