name: Retrieve Secrets and Trigger Build

on:
  repository_dispatch:
    types:
      - 00-retrieve-secrets

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: getRepo
        id: get-repo
        run: |
          echo "REPO=${{ github.event.client_payload.repo_url }}" >> $GITHUB_ENV
          echo "Value of REPO: $REPO"  # (DEBUG) Print the REPO value for tracking
          
      - name: Trigger Cross-Repository Dispatch
        env:
          SOME_EVENT: "01-start-build-and-push-image"
          REPO : ${{ github.event.client_payload.repo_url }}
          GITHUB_TOKEN: ${{ github.event.client_payload.github_token }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          KUBE_CREDENTIALS_CLIENTID: ${{ secrets.KUBE_CREDENTIALS_CLIENTID }}
          KUBE_CREDENTIALS_CLIENTSECRET: ${{ secrets.KUBE_CREDENTIALS_CLIENTSECRET }}
          KUBE_CREDENTIALS_TENANTID: ${{ secrets.KUBE_CREDENTIALS_TENANTID }}
          KUBE_CREDENTIALS_SUBSCRIPTIONID: ${{ secrets.KUBE_CREDENTIALS_SUBSCRIPTIONID }}
          
        run: |
          
          REPO_URL="${{ env.REPO }}"
          OWNER_NAME=$(echo $REPO_URL | cut -d'/' -f4)
          REPO_NAME=$(echo $REPO_URL | cut -d'/' -f5)
          URL="https://api.github.com/repos/${OWNER_NAME}/${REPO_NAME}/dispatches"
          curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --request POST \
            --data "{\"event_type\": \"$SOME_EVENT\", \"client_payload\": { \"docker_username\": \"$DOCKER_USERNAME\", \"docker_password\": \"$DOCKER_PASSWORD\" ,\"github_token\": \"$GITHUB_TOKEN\",\"kube_credentials_clientid\": \"$KUBE_CREDENTIALS_CLIENTID\", \"kube_credentials_clientsecret\": \"$KUBE_CREDENTIALS_CLIENTSECRET\",\"kube_credentials_tenantid\": \"$KUBE_CREDENTIALS_TENANTID\",\"kube_credentials_subscriptionid\": \"$KUBE_CREDENTIALS_SUBSCRIPTIONID\"}}" \
            "$URL"