name: Retrieve Secrets and Trigger Build

on:
  repository_dispatch:
    types:
      - 00-retrieve-secrets

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: getRepo
        id: get-repo
        run: |
          echo "REPO=${{ github.event.client_payload.repo_url }}" >> $GITHUB_ENV
          
      - name: Retrieve Secrets
        id: secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "KUBE_CREDENTIALS=${{ secrets.KUBE_CREDENTIALS }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Trigger Cross-Repository Dispatch
        env:
          AUTH_TOKEN: ${{ github.event.client_payload.github_token }}
          SOME_EVENT: "01-start-build-and-push-image"
          DOCKER_USERNAME: $DOCKER_USERNAME
          DOCKER_PASSWORD: $DOCKER_PASSWORD
          KUBE_CREDENTIALS: $KUBE_CREDENTIALS
        run: |
          REPO_URL="${{ env.REPO }}"
          curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $AUTH_TOKEN" \
            --request POST \
            --data "{\"event_type\": \"$SOME_EVENT\", \"client_payload\": { \"docker_username\": \"$DOCKER_USERNAME\", \"docker_password\": \"$DOCKER_PASSWORD\", \"kube_credentials\": \"$KUBE_CREDENTIALS\"}}" \
            "https://api.github.com/repos/$REPO_URL/dispatches"
