name: Retrieve Secrets and Trigger Build

on:
  repository_dispatch:
    types:
      - 00-retrieve-secrets

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: getRepo
        id: get-repo
        run: |
          echo "REPO=${{ github.event.client_payload.repo_url }}" >> $GITHUB_ENV
          echo "Value of REPO: $REPO"  # (DEBUG) Print the REPO value for tracking
          
      - name: Trigger Cross-Repository Dispatch
        env:
          SOME_EVENT: "01-start-build-and-push-image"
          REPO : ${{ github.event.client_payload.repo_url }}
          GITHUB_TOKEN: ${{ github.event.client_payload.github_token }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          KUBE_CREDENTIALS: ${{ secrets.KUBE_CREDENTIALS | base64 }}
        run: |
          
          REPO_URL="${{ env.REPO }}"
          OWNER_NAME=$(echo $REPO_URL | cut -d'/' -f4)
          REPO_NAME=$(echo $REPO_URL | cut -d'/' -f5)
          URL="https://api.github.com/repos/${OWNER_NAME}/${REPO_NAME}/dispatches"
          echo "REPO_URL: $REPO_URL"
          echo "REPO_NAME: $REPO_NAME"
          echo "OWNER_NAME: $OWNER_NAME"
          echo "Constructed URL: $URL"
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"
          echo "KUBE_CREDENTIALS: $KUBE_CREDENTIALS"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --request POST \
            --data "{\"event_type\": \"$SOME_EVENT\", \"client_payload\": { \"docker_username\": \"$DOCKER_USERNAME\", \"docker_password\": \"$DOCKER_PASSWORD\", \"kube_credentials\": \"$KUBE_CREDENTIALS\",\"github_token\": \"$GITHUB_TOKEN\"}}" \
            "$URL"