name: Docker Build and Push

on:
  repository_dispatch:
    types:
      - 01-start-build-and-push-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ github.event.client_payload.docker_username }}
          DOCKER_PASSWORD: ${{ github.event.client_payload.docker_password }}
          KUBE_CONFIG_DATA: ${{ github.event.client_payload.kube_config_data }}}
        run: |
          docker buildx create --use
          docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/<parameters.name>:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ${{ secrets.DOCKER_USERNAME }}/<parameters.name>:latest

      - name: Dispatch Event to Repo B (Trigger Kubernetes Apply)
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.repos.createDispatchEvent({
              repo: ${{ inputs.repo-url }},
              event_type: '02-apply-deploy',
              client_payload: {
                kube_config_data: process.env.KUBE_CONFIG_DATA,  # Pass Kubeconfig data to the third workflow
              }
            });

