name: Docker Build and Push

on:
  repository_dispatch:
    types:
      - 01-start-build-and-push-image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Environment Variables
        env:
          DOCKER_USERNAME: ${{ github.event.client_payload.docker_username }}
          DOCKER_PASSWORD: ${{ github.event.client_payload.docker_password }}
          KUBE_CREDENTIALS: ${{ github.event.client_payload.kube_credentials }}
          GITHUB_TOKEN: ${{ github.event.client_payload.github_token }}
          KUBE_CONFIG: ${{ github.event.client_payload.kube_config }}
        run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"
          echo "KUBE_CREDENTIALS: $KUBE_CREDENTIALS"
          echo "KUBE_CONFIG: $KUBE_CONFIG"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        env:
          DOCKER_USERNAME: ${{ github.event.client_payload.docker_username }}
          DOCKER_PASSWORD: ${{ github.event.client_payload.docker_password }}
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          DOCKER_USERNAME: ${{ github.event.client_payload.docker_username }}
          DOCKER_PASSWORD: ${{ github.event.client_payload.docker_password }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/<parameters.name>:latest

      - name: Trigger Kubernetes Apply Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KUBE_CREDENTIALS: ${{ github.event.client_payload.kube_credentials }}
          KUBE_CONFIG: ${{ github.event.client_payload.kube_config }}
        run: |
          # Trigger the workflow using the workflow_run event
          echo "::set-output name=triggering::true"  # Use this to trigger the workflow
          echo "KUBE_CREDENTIALS: $KUBE_CREDENTIALS"
          echo "KUBE_CONFIG: $KUBE_CONFIG"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          # Prepare the input payload with kube_credentials
          input_payload="{\"kube_credentials\":\"$KUBE_CREDENTIALS\",\"kube_config\":\"$KUBE_CONFIG\"}"

          # Trigger the "02-apply-deploy.yml" workflow in the same repository
          echo "Triggering '02-apply-deploy.yml' workflow..."
          echo "Workflow Run Payload: ${{ toJson(github.event) }}"
          echo "::set-output name=input_payload::$input_payload"
      