name: Apply Kubernetes YAML After Container Push

on:
  repository_dispatch:
    types: [02-repository-dispatch]

jobs:
  apply-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: akiojin/decode-base64-github-action@v0.1.0
        with:
          base64: <Base64>
          environment: ${{ github.event.client_payload.kube_credentials }}
      - run: |
          echo $DECODED

      - name: Azure Login
        uses: Azure/login@v1.4.6
        env:
          KUBE_CREDENTIALS : ${{ steps.decode-base64-step.outputs.decoded-kube-credentials }}
        with:
          creds: ${{ env.DECODED_KUBE_CREDENTIALS }}
      
      - name: Verify azure subscription
        run: |
          az account list
          
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.15.0' # default is latest stable
        id: install
      
      - name: Apply Kubernetes YAML
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ github.event.client_payload.kube_config }}
        with:
          args: apply -f ./deployments/deploy.yaml

      - name: Checkout repo
        uses: actions/checkout@v4

      # Perform Azure CLI operations
      - name: Azure CLI script
        run: |
          az logout
          az cache purge
          az account clear



  ## tenantID: cc39bc3b-9e6b-4556-aa3e-d2935e4801af
  ## subscriptionID: dcbec514-4dc8-4965-a962-b2b3b741ddfe
