name: Apply Kubernetes YAML After Container Push

on:
  workflow_run:
    workflows: ["Docker Build and Push"] # The name of your source workflow
    types:
      - completed

jobs:
  apply-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - uses: azure/login@v1
        env:
            KUBE_CREDENTIALS: ${{ github.event.inputs.kube_credentials }} # Set your Kubeconfig data secret
        with:
          creds: ${{ env.KUBE_CREDENTIALS }}

      - name: Apply Kubernetes YAML
        run: |
          kubectl apply -f path/to/your/kubernetes/yaml/file.yaml
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear


  ## tenantID: cc39bc3b-9e6b-4556-aa3e-d2935e4801af
  ## subscriptionID: dcbec514-4dc8-4965-a962-b2b3b741ddfe
