name: Apply Kubernetes YAML After Container Push

on:
  repository_dispatch:
    types: [02-repository-dispatch]

jobs:
  apply-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Decode and Set Kube Credentials
        id: decode-base64-step
        run: |
          DECODED_KUBE_CREDENTIALS=$(echo "${{ github.event.client_payload.kube_credentials }}" | base64 -d)
          echo "::set-output name=decoded-kube-credentials::$DECODED_KUBE_CREDENTIALS"
      
      - name: Use Decoded Credentials
        run: |
          # Accessing the decoded credentials from the previous step
          DECODED_CREDENTIALS="${{ steps.decode-base64-step.outputs.decoded-kube-credentials }}"
          echo "$DECODED_CREDENTIALS" > decoded_credentials.json  # Save to a file for multi-line JSON content
