name: Apply Kubernetes YAML After Container Push

on:
  repository_dispatch:
    types: [02-repository-dispatch]

jobs:
  apply-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Decode and Set Kube Credentials
        run: |
          echo "${{ github.event.client_payload.kube_credentials }}" | base64 -d
        
      
      - name: Azure Login
        uses: Azure/login@v1.4.6
        env:
          DECODED_STRING: ${{ steps.decode-base64-step.outputs.result }}
        run: |
          echo "Decoded String: $DECODED_STRING"
      
     