name: Apply Kubernetes YAML After Container Push

on:
  workflow_run:
    workflows: ["Docker Build and Push"] # The name of your source workflow
    types:
      - completed

jobs:
  apply-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Login to Azure using service principal credentials or a managed identity
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Set your Azure credentials secret

      - name: Apply Kubernetes YAML
        run: |
          kubectl apply -f ./deployments/deploy.yaml

      # Perform Azure CLI operations
      - name: Azure CLI script
        run: |
          az logout
          az cache purge
          az account clear



  ## tenantID: cc39bc3b-9e6b-4556-aa3e-d2935e4801af
  ## subscriptionID: dcbec514-4dc8-4965-a962-b2b3b741ddfe
