name: Apply Kubernetes YAML After Container Push

on:
  repository_dispatch:
    types: [02-repository-dispatch]

jobs:
  apply-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Decode and Set Kube Credentials
        id: decode-base64-step
        run: |
          echo "${{ github.event.client_payload.kube_credentials }}" | base64 -d
      - name: Use Decoded Base64 String
        env:
          DECODED_STRING: ${{ steps.decode-base64-step.outputs.result }}
        run: |
          echo "Decoded String: $DECODED_STRING"
     