name: Apply Kubernetes YAML After Container Push

on:
  repository_dispatch:
    types: [02-repository-dispatch]

jobs:
  apply-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Echo and Base64 Decode Kube Credentials
        run: |
          AZURE_CREDENTIALS=$(echo ${{ github.event.client_payload.kube_credentials }} | base64 -d)
          echo "Base64 Decoded Kube Credentials: $AZURE_CREDENTIALS"

      - name: Decode Kube Credentials
        run: |
          DECODED_KUBE_CREDENTIALS=$(echo "${{ github.event.client_payload.kube_credentials }}" | base64 -d)
          echo "Decoded Kube Credentials: $DECODED_KUBE_CREDENTIALS"
        id: decode_credentials
        env:
          DECODED_KUBE_CREDENTIALS: $DECODED_KUBE_CREDENTIALS

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ steps.decode_credentials.outputs.DECODED_KUBE_CREDENTIALS }} # Use the decoded credentials from the previous step

      - name: Verify azure subscription
        run: |
          az account list
      
      - name: Set env variables in terminal
        run: |
          $Env:ARM_CLIENT_ID = "$env:clientid"
          $Env:ARM_CLIENT_SECRET = "$env:clientsecret"
          $Env:ARM_SUBSCRIPTION_ID = "$env:subscriptionid"
          $Env:ARM_TENANT_ID = "$env:tenantid"
          
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.15.0' # default is latest stable
        id: install
      
      - name: Apply Kubernetes YAML
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ github.event.client_payload.kube_config }}
        with:
          args: apply -f ./deployments/deploy.yaml

      - name: Checkout repo
        uses: actions/checkout@v4
        
      # Perform Azure CLI operations
      - name: Azure CLI script
        run: |
          az logout
          az cache purge
          az account clear



  ## tenantID: cc39bc3b-9e6b-4556-aa3e-d2935e4801af
  ## subscriptionID: dcbec514-4dc8-4965-a962-b2b3b741ddfe
